Improved few phrases in RO Lang
altmp/altv-locales pull request #121
Opened 2021-09-05 22:18 UTC by vatto1337

2021-09-05 22:19 UTC, FabianTerhorst commented on package-lock.json
> +{
do we really want the package lock here?

2021-09-05 22:21 UTC, vatto1337 commented on package-lock.json
> +{
Good point

2021-09-06 11:21 UTC, C0kkie requested changes

2021-09-06 11:21 UTC, C0kkie commented on langs/ro.json
> +    "OUTPUT_VOLUME": "Volum microfon",
I dont think that is correctly translated

2021-09-07 18:34 UTC, merged